### ISSUE TITLE
Syncro: Possible to set fields?

### ISSUE THREAD

**Issue by masseym** [tier2tickets/Feedback#37] opened 2019-08-03 17:20 UTC
In Syncro, the ticket was created successfully, but it chose the wrong company.  Is it possible you select the company based on the computer name?

**Comment by grintor** [comment] 2019-08-06 15:47
It SHOULD decide which company to attach to based on the email address entered in the first page. It attaches to the company that has a contact in it with that email address. Can you tell me if that is not working?

**Comment by masseym** [comment] 2019-08-06 16:23
I used my email matt@masseymedia.com and it attaches to a company that doesn't have a domain.  I will go in and ensure that all of my companies have domains and try it again.

**Comment by TheNetworkSmith** [comment] 2019-08-07 16:11
If the email address is a contact for the customer then it autoassigns properly. If the email address only matches an email domain name rule for the customer then it will not.

**Comment by grintor** [comment] 2019-08-21 13:36
I am going to close this issue because I can't reproduce it, but if it's still causing you trouble call us and we can look at it together

(833) 328-8866

**Closed by grintor** 2019-08-21 13:36 UTC
