### ISSUE TITLE
Window location with multiple monitors

### ISSUE THREAD

**Issue by TheNetworkSmith** [tier2tickets/Feedback#33] opened 2019-08-02 13:22 UTC
When the workstation has 2 monitors the ticket window for helpdeskbutton shows up in the middle  split between the two windows. It does not remember the window position if moved and then launched again.

**Comment by apermenter** [comment] 2019-08-02 17:03
Duplicate of #3 merging to that.

**Closed by apermenter** 2019-08-02 17:03 UTC
Labels: GUI/MSI, bug
