### ISSUE TITLE
F12 Key

### ISSUE THREAD

**Issue by elcopeland** [tier2tickets/Feedback#30] opened 2019-08-01 16:44 UTC
> Just got a test system setup and I noticed by F12 doesn't work. I can click the desktop shortcut and that works fine but just hitting F12 doesn't.

**Comment by grintor** [comment] 2019-08-09 15:38
I finally got some time to look at the F12 bug and what I found is interesting. First though, let me let you in on the secret on how the F-key trigger works because it's really kind of cheating haha. If you right click the desktop icon and click properties > shortcut. You will find that windows has a "shortcut key" field. It's actually a property of the shortcut file on the desktop that you can use to launch any app that's on the desktop, and we just set that property using the installer when the shortcut is created. Mostly, people put key-combos in there like ctrl-shift-l or whatever, but we found that windows will also allow function keys (although, that's the only single-key options windows will permit). And while windows will let you enter F1 through F12 into that box and save it, F12 does not actually work.

It seems to be a bug in windows itself and I have tested it on a few systems. I have confirmed that F1 though F11 work though. So, for that reason I have modified the installer to only allow for setting F1 - F11. Of course you don't actually have to rely on the installer to set that. You could, for example, manually set it to a key-combo. But having it assigned to a single button allows for putting a sticker on that button to make it super easy for people.

If you want my suggestion for a new function key to pick, I think F9 or F4 are the least likely to interfere with other apps a user might be using.

Let me know if this helps!

Thanks,
Chris

**Closed by grintor** 2019-08-09 15:38 UTC
Labels: GUI/MSI, bug
