### ISSUE TITLE
Multiple user access

### ISSUE THREAD

**Issue by elcopeland** [tier2tickets/Feedback#24] opened 2019-08-01 15:57 UTC
Create method for allowing multiple users from same organization access to portal. 

> I don’t see the ability to setup multiple users under the organization except for accessing reports that come in via text message authentication. Are there any plans to have more than one user account per organization that we can all manage the customizations and billing? Or should we make this a generic login and secure password shared out with everyone.

> Ability to have multiple logins that point to the same account--right now the login email is also the email that receives the support requests.  I would love to split that up and also be able to add my other techs so they can sign in.

**Comment by apermenter** [comment] 2019-08-02 16:59
on roadmap, closing as not a bug.

**Closed by apermenter** 2019-08-02 16:59 UTC
Labels: account portal, enhancement
